CREATE TABLE vehicles (
    id INT(11) NOT NULL AUTO_INCREMENT,
    plate VARCHAR(10) NOT NULL,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    year INT(11) NOT NULL,
    daily_rate DECIMAL(10,2) NOT NULL,
    status ENUM(
        'AVAILABLE',
        'RENTED',
        'MAINTENANCE'
    ) NOT NULL DEFAULT 'AVAILABLE',
    category_id INT(11) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);